### ISSUE TITLE
error with payload as argument

### ISSUE THREAD

**Issue by Damontir** [Jacques44/node-red-contrib-bigssh#10]
Hi!

i try to parse a payload from a function to BigSSH but i receive some errors like this:

convert-im6.q16: unable to open image `glob': No such file or directory @ error/blob.c/OpenBlob/2701.convert-im6.q16: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.convert-im6.q16: no images defined `/media/fritzbox/SanDisk-CruzerBlade-01/ZR1/yesterday.gif' @ error/convert.c/ConvertImageCommand/3258.

msg.payload is: "convert -delay 5 -loop 0 /media/fritzbox/SanDisk-CruzerBlade-01/ZR1/2019-02-07*.jpg /media/fritzbox/SanDisk-CruzerBlade-01/ZR1/yesterday.gif"

When i write the payload directly as command, than it work.

Where is the Problem?

[{"id":"4e4da10.4ab716","type":"debug","z":"7b84e3da.f9974c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1870,"y":180,"wires":[]},{"id":"718dfe8.1b12c","type":"debug","z":"7b84e3da.f9974c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1710,"y":120,"wires":[]},{"id":"d513748.da04d88","type":"inject","z":"7b84e3da.f9974c","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1100,"y":180,"wires":[["aa7a4a22.7064d8"]]},{"id":"aa7a4a22.7064d8","type":"moment","z":"7b84e3da.f9974c","name":"","topic":"","input":"payload","inputType":"msg","inTz":"Europe/Berlin","adjAmount":"0","adjType":"days","adjDir":"subtract","format":"YYYY-MM-DD","locale":"de_DE","output":"payload","outputType":"msg","outTz":"Europe/Berlin","x":1300,"y":180,"wires":[["fb13530c.0f726"]]},{"id":"fb13530c.0f726","type":"function","z":"7b84e3da.f9974c","name":"","func":"msg.payload = \"convert -delay 5 -loop 0 /media/fritzbox/SanDisk-CruzerBlade-01/ZR1/\"+msg.payload+\"*.jpg /media/fritzbox/SanDisk-CruzerBlade-01/ZR1/yesterday.gif\";\nreturn msg;","outputs":1,"noerr":0,"x":1490,"y":180,"wires":[["718dfe8.1b12c","9c78d3d9.b296e"]]},{"id":"9c78d3d9.b296e","type":"bigssh","z":"7b84e3da.f9974c","name":"oPi","commandLine":"","commandArgs":"","minError":1,"minWarning":"5","noStdin":false,"format":"utf8","payloadIsArg":true,"myssh":"9d54a147.ddccf","x":1650,"y":180,"wires":[["4e4da10.4ab716"],[],["4e4da10.4ab716"]]},{"id":"9d54a147.ddccf","type":"SSH_Credentials","z":"","host":"192.168.178.79","port":"22","userlabel":"robert@192.168.178.79"}]

**Comment by Jacques44** [comment]
Hello,

Please replace convert using its full path on the remote system.
