### ISSUE TITLE
Execute several commands at once

### ISSUE THREAD

**Issue by TinusK** [Jacques44/node-red-contrib-bigssh#11]
Question. How could I send several commands at once? For example:
command 1: influx
command 2: show databases
command 3: exit

The above commands starts the influx database CLI. Then lists the databases and then exits.
How would I do this with bigssh?

Thanks
Tinus

**Comment by Jacques44** [comment]
Hello,

you can send multiple commands	if they are system ones…
Here is an example: echo first; echo second; echo end

In your example, these seems to be several arguments of one command

You can use another « big » module names bigfile.

1. You put the 3 commands in a file
2. You set a bigfile node to read your file, checking payload is or not a filename whether or not you specify the filename in the configuration node or from an inject node
3. You set « output » as a buffer
4. You connect this node to the input of the ssh command

et voilà

Regards
