### ISSUE TITLE
sending command line args

### ISSUE THREAD

**Issue by spanout** [Jacques44/node-red-contrib-bigssh#14]
Excuse this issue if I am being stupid.  I am executing a remote python script on a pi. I can do this really well with BIG SSH but I want to add args after the script name. If I put this in the command line, it works, I want to get the args from mqtt and I have tried to add them as payload but this gives me "TypeError: Cannot read property 'replace' of undefined"  I also tried to put them in a template. What is the correct way to do this.

thanks for your help and this is a great Node !

**Comment by Jacques44** [comment]
Hello,

no question is stupid :-)

You have a checkbox: « payload is an argument » . If checked, the node takes any incoming message as an argument for your command

thanks and Regards

**Comment by spanout** [comment]
Thanks for your prompt reply. This is exactly what I thought, but I am getting "TypeError: Cannot read property 'replace' of undefined"

The node is configured like the attachments
![BIG SSH](https://user-images.githubusercontent.com/1569544/61078307-3fea4980-a418-11e9-8ff1-da5d82a8e00f.png)

A debug on the msg.payload prior to the bigSSH node is:

"#0000ff #0000ff"  

so I would expect 2 arguments to go through... is that correct?

**Comment by spanout** [comment]
OK, figured it out, remove the # of the html colour codes and all works, so not an issue
