### ISSUE TITLE
Error: Return code 1

### ISSUE THREAD

**Issue by IsaTTeN** [Jacques44/node-red-contrib-bigssh#15]
Hello

I´m having problems with this SSH conection to Hassio. If I send this command:

`hassio help `

I get in the node´s output the reply that I get in Putty.

But if I use this command:

`hassio addons logs core_check_config`

I get this error: 

Error: Return code 1
Payload: Unexpected server response

If I type the same command in Putty I get this response:
![image](https://user-images.githubusercontent.com/20249994/65376352-d481eb00-dc96-11e9-83f7-d9f02bc807dd.png)

Can you give some advice?

Best regards

**Comment by Jacques44** [comment]
Hello,
really sorry but I don't know anything about "hassio". This code is for node-red
Usually, node modules are installed using npm not pip...

Regards
