### ISSUE TITLE
More SSH commands

### ISSUE THREAD

**Issue by Schubbie** [Jacques44/node-red-contrib-bigssh#16]
Hello,
to reconfigure my Security Gateway automatically it is necessary to submit more commands in one with SSH.

```
configure
edit service dns
set forwarding options host-record=abc.domain.de,192.168.153.1
set forwarding options host-record=def.domain.de,192.168.153.2
set forwarding options host-record=ghi.domain.de,192.168.153.3
set forwarding options host-record=jkl.domain.de,192.168.153.222
set forwarding options host-record=mno.domain.de,192.168.210.50

exit
commit
save

exit
exit

```

Is it possible to realise this?

With best regards
Andreas

**Comment by Jacques44** [comment]
Hello,

please check another issue which was closed: https://github.com/Jacques44/node-red-contrib-bigssh/issues/11 <https://github.com/Jacques44/node-red-contrib-bigssh/issues/11> and tell me

Regards

**Comment by Schubbie** [comment]
Hello,
thanks for your response.
I can´t send any correct command to that device.

`vbash: configure: command not found`
and
`24.9.2019, 01:58:42node: b1677874.620838
msg : error
"Error: Return code 127"`

This errors came if i only type "configure" in BigSSH and if i try it with the file (UTF 8).
If i type the commands in putty all works fine.

Any idea?

With best regards
Andreas

**Comment by Jacques44** [comment]
Hello,

please don’t forget that when connected trough putty, you have all variables set in your environnement. The shell knows then where to search for binaries using the PATH variable
When connected though bigssh, you have nothing set.

Please try using the full path for each command
You can find them by typing which in putty

Regards
