### ISSUE TITLE
Error: Unsupported key exchange algorithm

### ISSUE THREAD

**Issue by Shalvan** [Jacques44/node-red-contrib-bigssh#17]
Hi there,

I have a problem with connecting with Your node to my server throu ssh, the node gives me this error:
Error: Unsupported key exchange algorithm
I can connect by console but needed to add:
HostKeyAlgorithms=+ssh-dss
into my /etc/ssh_config file

I tried to type this into Your node with no luck.

How i can add this algorithm so i can connect ?

The server im trying to connect to is older HP-Proliant g7 server with ilo3

**Comment by Jacques44** [comment]
Hello, this node relies on ssh2 (https://www.npmjs.com/package/ssh2)
All it can supports is from this package... 

In the node configuration, you've a "Key Exchange Algorithms", please set it to "ssh-dss"

**Comment by nirkons** [comment]
Same problem, I've tried over a dozen key exchange algorithms, ciphers etc...
before everything was working (before the node had all these configurations), now I can't find a supported one
