### ISSUE TITLE
Command Line Arguments

### ISSUE THREAD

**Issue by ryancasler** [Jacques44/node-red-contrib-bigssh#18]
Okay, I'm sorry, but I can't figure this out.  If I put this in the command line, it works perfectly:
vlc --play-and-exit http://url.of.sound.fle

But, if I have it set up like this, it doesn't work.

![image](https://user-images.githubusercontent.com/30270489/84932742-c389cd00-b0a2-11ea-91dd-06960e4896f5.png)

What is the deal?  How am I supposed to pass the payload to be appended to the end of the command?

Update:
You also have to have "don't send payload to the command" checked?!?!   You really should include that in the notes for the node.

**Comment by Jacques44** [comment]
Hello,
please set the full path of the vlc command as once connected, ssh doesn't know about any path

Tell me

**Comment by ryancasler** [comment]
I did, that wasn't the problem.  The problem was that in addition to "Payload is an argument", you also have to have "Do not send payload to the command" checked in order for the whole command to be sent via SSH.  Not very intuitive.
