### ISSUE TITLE
Any example flow please ?

### ISSUE THREAD

**Issue by titusece** [Jacques44/node-red-contrib-bigssh#2]
Hi,
I'm trying to use bigssh in node-red ?
Just I want some example flow to understand how to connect, etc.,

Getting the following error.

Error: privateKey value does not contain a (valid) private key

also not sure what to use for "Private key path" and "Pass phase"

Regards,
Titus S.

**Comment by titusece** [comment]
Given this "/home/pi/.ssh/id_rsa" location for "Private key" and got the below error.

Error: All configured authentication methods failed

**Comment by Jacques44** [comment]
Hello,
you need to know first how ssh works. :-)

The private key is used to authenticate against an host you've previously allowed to.

To do this, you need to add your public key to a file named .ssh/authorized_keys on the remote host. (with the most restrictive rights)
Once done, you need to test the remote connection as you'll first have a warning message.

If all is ok using the command line, you should use this node
I'll try to put an example

Regards

**Comment by titusece** [comment]
Thanks Jacques.
I'm able to do ssh in command line.

Let me try to provide the following file as Private key and update you.
/home/pi/.ssh/authorized_keys

Also looking some example, thanks.

**Comment by titusece** [comment]
I have tried to use the " /home/pi/.ssh/authorized_keys" as private key, didn't help.

I am trying to do ssh connection from my Rpi board to my laptop.

Here is the flow I used to test.

[{"id":"93ce9864.0d30c","type":"bigssh","z":"d8daab5d.a1b2","name":"","commandLine":"ls /home/","commandArgs":"","minError":1,"minWarning":1,"noStdin":true,"format":"utf8","payloadIsArg":false,"myssh":"5ed6b566.dbb97c","x":584.25,"y":197,"wires":[["a9555ead.d74e98"],["a9555ead.d74e98"],["a9555ead.d74e98"]]},{"id":"a9555ead.d74e98","type":"debug","z":"d8daab5d.a1b2","name":"","active":true,"console":"false","complete":"false","x":901.25,"y":260.316650390625,"wires":[]},{"id":"455cb881.5cc7f","type":"inject","z":"d8daab5d.a1b2","name":"go","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":336.25,"y":238.43331909179688,"wires":[["93ce9864.0d30c"]]},{"id":"5ed6b566.dbb97c","type":"SSH_Credentials","z":"d8daab5d.a1b2","host":"192.168.0.107","port":"22","userlabel":"titus@192.168.0.107"}]

And got the below error in debug node.

_msg.payload : undefined(undefined)
msg.payload : undefined(undefined)
msg : errorError: privateKey value does not contain a (valid) private key_

Can you please help ?

Thanks for your support.

**Comment by Jacques44** [comment]
Hello,
I've copy/paste your code.
I can't see the private key reference in the ssh credentials box
You've set the host and port but no key

Regards

2016-09-19 19:12 GMT+02:00 Titusrathinaraj Stalin <notifications@github.com>
:

**Comment by titusece** [comment]
Hi  Jacques,
Thanks for your reply.
I have given the private key file with location, but not exported in flow.
I also tried to import the given flow, I'm also not able to see the key.
Once I again I given the private key and exported, not able to see it, it seems, not allowed huh?

Anyways you can try that flow and add the private and check my behavior and what I requested (able to login and do the command via ssh shell)

Thanks.

Regards,
Titus S.

**Comment by Jacques44** [comment]
Hello,
the private key should be private and not readable by others.
Depending on how node-red is launched, I think the node-red can't read your key.

In node-red-contrib-bigssh code, You should probably see an error message in node-red console...

Regards

**Comment by titusece** [comment]
Same error I have got in node-red console too.

**Comment by Jacques44** [comment]
Hello, what's up?

**Comment by Jacques44** [comment]
Please feel free to reopen
Regards
