### ISSUE TITLE
Second output is undefined always

### ISSUE THREAD

**Issue by alexsahka** [Jacques44/node-red-contrib-bigssh#20]
###2 send start/end messages as well as statuses

That means it uses a second output to give control states (start/end/running and error) control messages

When run BigSSH I got undefined from the second output always.

![image](https://user-images.githubusercontent.com/7469537/93509455-997bbd00-f8d4-11ea-92de-ba3a35c32eb6.png)

![image](https://user-images.githubusercontent.com/7469537/93509478-a39dbb80-f8d4-11ea-9196-86b4055394f0.png)

**Comment by Jacques44** [comment]
Please try to view the full msg. Data is in msg.control
