### ISSUE TITLE
Injecting command including pipe "|"

### ISSUE THREAD

**Issue by bkdfkup** [Jacques44/node-red-contrib-bigssh#21]
I have an issue where the BIGSSH node will not accurately inject a command payload (from an external node) when a pipe ("|") is used to process the output of the initial command. All simple/single commands work fine when injected.

Example: "whois xxx.xxx.xxx.xxx | grep netname"

IF I enter the command into the BIGSSH node directly it outputs correctly, however if inject a command to the node as an argument, it fails. I particularly need to inject this from outside BIGSSH due to the IP address not being static.

Grateful for assistance. Thanks in advance.

**Comment by Jacques44** [comment]
Hello, I've made a special version of bigssh for you :-)
I'll now be possible to send a json value as a payload and set the command to a template string
I'm having dinner right now, will publish after !

![Screen Shot 2020-11-25 at 18 50 01](https://user-images.githubusercontent.com/18165555/100264522-3b5ffb80-2f4f-11eb-8b89-a75de33f22e7.png)

**Comment by Jacques44** [comment]
Published.

**Comment by bkdfkup** [comment]
You legend!! Thanks so much for spending the time on it (and the nodes in general). I'm about to head to work, but will try test tonight 👍

**Comment by Jacques44** [comment]
Time for movie before night here, you'll tell me if it's ok
Have a nice workday!

**Comment by bkdfkup** [comment]
Thanks! Dumb question, however there is no update in the Node-RED palettes for BIGSSH. Do i need to do a manual NPM install?

**Comment by Jacques44** [comment]
my pleasure, I used to npm update to get the latest. I've published it, should work

**Comment by bkdfkup** [comment]
One last question, are you able to share the flow pictured above so i can learn how the bigline and bigstatus nodes function?

**Comment by Jacques44** [comment]
Just done :-)

**Comment by bkdfkup** [comment]
You are amazing. I shall mark this issue as closed 👍
