### ISSUE TITLE
bash: ${payload.ip}: bad substitution

### ISSUE THREAD

**Issue by bkdfkup** [Jacques44/node-red-contrib-bigssh#23]
Hey again!

I have deployed 1.2.7 via npm as advised, and checking the version via command line verifies the correct version is installed, however in the node-red palette list it shows ver 1.2.4. As shown here:

![image](https://user-images.githubusercontent.com/74683396/100294476-04cfc280-2fdb-11eb-9481-0fd4e9832b22.png)
vs
![image](https://user-images.githubusercontent.com/74683396/100294518-203acd80-2fdb-11eb-94c8-f545185ece44.png)

Potentially as a result of this i cannot get substituting the payload to function correctly, getting the "bad substitution" error, even with your example flow.

Examples:
![image](https://user-images.githubusercontent.com/74683396/100294373-b7ebec00-2fda-11eb-8c8a-a1dd09c9d3b1.png)

Thanks in advance for any advice!

**Comment by Jacques44** [comment]
Hello,

Did you restart node-red?

Btw, can you give me informations on how do you run node-red? System?

Regards

**Comment by bkdfkup** [comment]
Hi!

 Yes I restarted node red after installing the new version. No change. Did an "npm uninstall" and reinstall (and reboot), no change. Versions as captured in the first post if this issue. 

I have the node-RED configured to start as a service upon boot. 

Hope that helps 🤷

Thanks!

**Comment by Jacques44** [comment]
That sounds strange.

By my side, I’m using
- node-red v1.2.6
- node.js v 10.21.0

It seems that you node-red uses another node-modules directory 

Maybe you can check your file system for node-red-contrib-bigssh directories
You can check the node version by opening the package.json file inside. You should see 1.2.7

I don’t see the node version in the palette...

**Comment by Jacques44** [comment]
I’ve downgraded my node-red-contrib-bigssh installation to 1.2.4 and I’m getting the same error messages as yours.

So I think node-red is still using another node-red-contrib-bigssh installation which has not been upgraded…

**Comment by bkdfkup** [comment]
Interesting. I am on the same ver of node red, and am on node.js v15.2.1. 

I'll keep searching for the alternate node dir....

**Comment by bkdfkup** [comment]
So... you have put me on the right path, and the steps listed here https://nodered.org/docs/user-guide/runtime/adding-nodes (in particular running the npm commands from ~/.node-red specifically (as opposed to the root dir) fixed the issue!

**Comment by Jacques44** [comment]
Great :-)

**Comment by bkdfkup** [comment]
Thanks very much! Closing this issue.
