### ISSUE TITLE
Error using Private Key - unsupported key format

### ISSUE THREAD

**Issue by xppx99** [Jacques44/node-red-contrib-bigssh#24]
Hi there, 

I'm trying to use the PrivateKey method for autentication on my remote server, but I'm failing to login using this node. The node returns "Cannot parse privatKey: unsupported key format". 

I've just generated the key using the command "ssh-keygen" and I've check that I can ssh to remote site using the key with success. Also in my opinion the key has a correct format: 
-----BEGIN OPENSSH PRIVATE KEY-----
Lots of lines with random chars 
-----END OPENSSH PRIVATE KEY-----

![image](https://user-images.githubusercontent.com/52202278/101222483-c5137580-3681-11eb-85ff-5e51cbc6fc43.png)

The node settings I think are fine: 
![image](https://user-images.githubusercontent.com/52202278/101222664-28050c80-3682-11eb-9697-e624e61d233f.png)

Can you please help me? 
Thanks in advance

**Comment by Jacques44** [comment]
Hello,
this node relies on ssh2 which is a separate module.

You should try to generate your public/private key pair with a command such as:

ssh-keygen -m PEM -t rsa

That will generate a compatible key

Have a nice day

**Comment by Jacques44** [comment]
Hello,
this node relies on ssh2 which is a separate module.

You should try to generate your public/private key pair with a command such as:

ssh-keygen -m PEM -t rsa

That will generate a compatible key

Have a nice day
