### ISSUE TITLE
Feature Request - Enable dynamic host as node Input msg.payload.host 

### ISSUE THREAD

**Issue by sudoritz** [Jacques44/node-red-contrib-bigssh#28]
Feature IDEA --  IP as Dynamic {msg.payload.host}

Enable  a new input to have host as the input as dynamic. and still use the same SSH-Credentials supplied.

**Comment by Jacques44** [comment]
Hello, added in 1.2.8
You can override the host value by setting msg.config.host

Please consider tips

**Comment by pokryva** [comment]
> Hello, added in 1.2.8 You can override the host value by setting msg.config.host
> 
> Please consider tips


Hi,
Does this still work in 1.2.9? I'm having problems overriding host. I created one valid credentials configuration, other hosts use the same username/password. I was hoping to override just host with msg.config.host. It does not work, it keeps connectning to the host specified in "credentials" configuraton... Any ideas?
