### ISSUE TITLE
Feature Request (Follow on from #28)

### ISSUE THREAD

**Issue by My-Random-Thoughts** [Jacques44/node-red-contrib-bigssh#29]
Can you supply the host name used in the output please.

I am wanting to loop though a list of host names to run a command and split on the output for each host.
Thanks

**Comment by Jacques44** [comment]
Hello, if I understand well, you've got an array of host you will loop on and call bigssh for each one?
bigssh will give you its configuration on the control output, the 3rd one. You can try by connecting a debug node and display "msg.control.config.host"

**Comment by My-Random-Thoughts** [comment]
That is correct, I want to try and simplify the flow.
I did connect separate debugs to all nodes and I am getting zero output from the third output.  1 and 2 are working OK, but not 3.  I do have "complete msg object" selected.

I have v1.2.8 installed on NRv1.3.5

**Comment by Jacques44** [comment]
sorry, control is the second

**Comment by My-Random-Thoughts** [comment]
I am not getting the msg.control.config.host value:

`{"_msgid":"51fc4976f26b0436","payload":1626641097461,"topic":"","control":{"config":{"id":"33d019367cc91ca9","type":"bigssh","name":"","commandLine":"uname -a","commandArgs":"","minError":1,"minWarning":1,"noStdin":true,"format":"utf8","payloadIsArg":false,"myssh":"e491f93d.13b1a8","checkpoint":100,"status_rate":1000,"control_rate":1000,"start_point_type":"filename"},"size":0,"records":0,"start":"2021-07-18T20:44:57.462Z","speed":0,"control":{"state":"standalone"},"state":"start","message":"running..."}}`

**Comment by Jacques44** [comment]
I set the host on its input
![Screen Shot 2021-07-18 at 22 47 55](https://user-images.githubusercontent.com/18165555/126081721-ce2bf395-0614-44b6-9d02-bf7aa588b59d.png)

**Comment by My-Random-Thoughts** [comment]
Maybe that is where I was going wrong, I have it pre-populated for testing!
Sorry, it's working now.
Thank you

**Comment by Jacques44** [comment]
No problem. Maybe the node should send the whole embedded configuration on its output. By the way, tell me if this is not ok for you?
