### ISSUE TITLE
Execute remote command as root

### ISSUE THREAD

**Issue by spry-salt** [Jacques44/node-red-contrib-bigssh#38]
I must be missing something obvious, sorry. Is there a way to execute a remote command as root/sudo? Normally ssh -t would help but I cant find a way to do that. Can anyone help please?

**Comment by Jacques44** [comment]
Hello, I've set up bigssh to execute a simple "sudo id" and it works...
I needs your user to be sudoer on the remote system

**Comment by spry-salt** [comment]
It seems ok for simple commands but not to run a shell script as su. Not to worry, I found another way. Thanks.
