### ISSUE TITLE
Passphrase is not saved

### ISSUE THREAD

**Issue by misosec** [Jacques44/node-red-contrib-bigssh#4]
Hello,
passphrase/password is not saved. I am not using encryption keys, just username and password.

Thank you.

**Comment by misosec** [comment]
Any idea how to fix this? 
Thanks again.

**Comment by Jacques44** [comment]
Hello, the bigssh node only works with private/public key method authentication not password

**Comment by Jacques44** [comment]
Hello, i'm checking for password authentication
Regards
