### ISSUE TITLE
getting "Error getting tty, exiting" running BigSSH

### ISSUE THREAD

**Issue by jonsieck** [Jacques44/node-red-contrib-bigssh#9]
hi 

i have tried to run a SSH session against i "Linux" appliance.
In the console it is not possible to start a Shell and it returns "Error getting tty, exiting"
I am a little Newbie into js - but have trief to figure out if it's possible to add an argument that disable
default shell on connection. or do i have to mod. the SSH module ?

**Comment by Jacques44** [comment]
Hello, you should use "-n" option to avoid stdin. Please tell me

**Comment by jonsieck** [comment]
You mean as a -
commandArgs":"  -n “.  ??


Mvh Jon F Sieck, sendt fra min mobile !


Den 7. mar. 2019 kl. 20.14 skrev Jacques W <notifications@github.com<mailto:notifications@github.com>>:


Hello, you should use "-n" option to avoid stdin. Please tell me
